// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLxF9d9M0LU_aWnEZwwOdYvSqPm_X_Puo',
    appId: '1:722726449265:web:51e0f6518d378db622ebd0',
    messagingSenderId: '722726449265',
    projectId: 'huddleupproject-c446d',
    authDomain: 'huddleupproject-c446d.firebaseapp.com',
    storageBucket: 'huddleupproject-c446d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBpcejda4EtPRPCd-r1rFbSX46hlF1bVM',
    appId: '1:722726449265:android:87b85591b5f2406222ebd0',
    messagingSenderId: '722726449265',
    projectId: 'huddleupproject-c446d',
    storageBucket: 'huddleupproject-c446d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtp2vjesi--AHfowDqwdB6eUj8xrnuWNA',
    appId: '1:722726449265:ios:9991a96bff1ac8da22ebd0',
    messagingSenderId: '722726449265',
    projectId: 'huddleupproject-c446d',
    storageBucket: 'huddleupproject-c446d.appspot.com',
    iosClientId: '722726449265-t2diqetcd5kdvo7pqhgmvv2iu477igv4.apps.googleusercontent.com',
    iosBundleId: 'com.example.huddleUpProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtp2vjesi--AHfowDqwdB6eUj8xrnuWNA',
    appId: '1:722726449265:ios:44be45f1db852f6422ebd0',
    messagingSenderId: '722726449265',
    projectId: 'huddleupproject-c446d',
    storageBucket: 'huddleupproject-c446d.appspot.com',
    iosClientId: '722726449265-3pamaka9033rgvl13l12psa1su0esv6u.apps.googleusercontent.com',
    iosBundleId: 'com.example.huddleUpProject.RunnerTests',
  );
}
